#!/usr/bin/env python3
"""Validate the static Joyce reader data set.

The validator knows about the legacy Ulysses layout through ``works.json``
but validates it through the same work/chapter/note model as the generated
Portrait data.  It is intentionally dependency-free so it can run in a
fresh checkout before a browser is opened.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
import unicodedata
from html.parser import HTMLParser
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
WORKS_PATH = BASE_DIR / "data" / "works.json"


def load_json(path: Path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def visible_text(source: str) -> str:
    class TextParser(HTMLParser):
        BLOCKS = {"p", "h1", "h2", "h3", "h4", "blockquote", "pre", "li"}

        def __init__(self) -> None:
            super().__init__(convert_charrefs=True)
            self.parts: list[str] = []

        def handle_starttag(self, tag, attrs):
            if tag.lower() == "br":
                self.parts.append("\n")

        def handle_startendtag(self, tag, attrs):
            self.handle_starttag(tag, attrs)

        def handle_endtag(self, tag):
            if tag.lower() in self.BLOCKS:
                self.parts.append("\n\n")

        def handle_data(self, data):
            self.parts.append(data)

    parser = TextParser()
    parser.feed(source or "")
    parser.close()
    return "".join(parser.parts)


def normalized(value: str) -> str:
    """Match the build-time comparison rules without changing displayed text."""
    quote_map = {
        "“": '"', "”": '"', "„": '"', "‟": '"', "«": '"', "»": '"',
        "‘": "'", "’": "'", "‚": "'", "‛": "'",
    }
    dash_to_space = set("–—―")
    hyphens = set("‐‑‒−-")
    result: list[str] = []
    for original in value or "":
        for char in unicodedata.normalize("NFKC", original):
            if char in {"\u00ad", "\u200b", "\u200c", "\u200d", "\ufeff"}:
                continue
            if char.isspace() or char in dash_to_space:
                replacement = " "
            elif char == "…":
                replacement = "..."
            elif char in hyphens:
                replacement = ""
            else:
                replacement = quote_map.get(char, char)
            for output in replacement:
                if output == " " and result and result[-1] == " ":
                    continue
                result.append(output)
    return "".join(result).strip().casefold()


class StructureParser(HTMLParser):
    """Collect annotation references and detect malformed/nested anchors."""

    VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[str] = []
        self.annotation_depth = 0
        self.references: list[tuple[str, list[str], str]] = []
        self.errors: list[str] = []

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrs_map = {key: value or "" for key, value in attrs}
        if tag == "a" and attrs_map.get("data-type") == "annotation":
            if self.annotation_depth:
                self.errors.append("nested annotation anchor")
            self.annotation_depth += 1
            raw = attrs_map.get("data-notes", "")
            ids = [item for item in re.split(r"[,\s]+", raw) if item]
            href = attrs_map.get("href", "")
            if href and href not in ids:
                ids.insert(0, href)
            self.references.append((href, ids, raw))
        if tag not in self.VOID:
            self.stack.append(tag)

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag.lower() not in self.VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag == "a" and self.annotation_depth:
            self.annotation_depth -= 1
        if tag in self.stack:
            # HTML generated by the build should be properly nested. Popping
            # through a mismatch still lets us report a useful error.
            if self.stack[-1] != tag:
                self.errors.append("unbalanced </%s>" % tag)
                while self.stack and self.stack[-1] != tag:
                    self.stack.pop()
            if self.stack:
                self.stack.pop()
        else:
            self.errors.append("orphan </%s>" % tag)

    def close(self):
        super().close()
        if self.stack:
            self.errors.append("unclosed tags: " + ", ".join(self.stack[-5:]))


def work_paths(work: dict, work_id: str) -> tuple[Path, Path, Path]:
    legacy = work.get("legacy_paths") or {}
    chapter_dir = BASE_DIR / legacy.get("chapters", f"data/works/{work_id}/chapters")
    note_dir = BASE_DIR / legacy.get("notes", f"data/works/{work_id}/notes")
    media_dir = BASE_DIR / legacy.get("media", f"data/works/{work_id}/media")
    return chapter_dir, note_dir, media_dir


def validate() -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    try:
        manifest = load_json(WORKS_PATH)
    except Exception as exc:
        return [f"cannot read {WORKS_PATH}: {exc}"], []
    if not isinstance(manifest, list):
        return ["data/works.json must contain an array"], []

    works_by_id: dict[str, dict] = {}
    chapters_by_id: dict[str, tuple[str, dict, Path]] = {}
    notes_by_id: dict[str, tuple[str, dict, Path]] = {}
    media_by_work: dict[str, set[str]] = {}

    for work in manifest:
        work_id = work.get("id") if isinstance(work, dict) else None
        if not work_id:
            errors.append("work without an id in data/works.json")
            continue
        if work_id in works_by_id:
            errors.append(f"duplicate work id: {work_id}")
            continue
        works_by_id[work_id] = work
        chapter_dir, note_dir, media_dir = work_paths(work, work_id)
        media_by_work[work_id] = {
            path.stem for path in media_dir.glob("*.json") if path.name != "index.json"
        }
        seen_chapters: set[str] = set()
        for descriptor in work.get("chapters", []):
            chapter_id = descriptor.get("id") if isinstance(descriptor, dict) else None
            if not chapter_id:
                errors.append(f"{work_id}: chapter descriptor without id")
                continue
            if chapter_id in seen_chapters:
                errors.append(f"{work_id}: duplicate chapter id {chapter_id}")
            seen_chapters.add(chapter_id)
            if chapter_id in chapters_by_id:
                errors.append(f"duplicate chapter id across works: {chapter_id}")
            path = chapter_dir / f"{chapter_id}.json"
            if not path.exists():
                errors.append(f"{work_id}: missing chapter file {path.relative_to(BASE_DIR)}")
                continue
            try:
                chapter = load_json(path)
            except Exception as exc:
                errors.append(f"{path.relative_to(BASE_DIR)}: invalid JSON ({exc})")
                continue
            if chapter.get("id") != chapter_id:
                errors.append(f"{path.relative_to(BASE_DIR)}: id does not match manifest")
            if chapter.get("work_id") not in (None, work_id):
                errors.append(f"{path.relative_to(BASE_DIR)}: wrong work_id")
            if chapter.get("work_id") is None:
                # The original Ulysses files predate the work-aware schema;
                # the browser adds this field when it loads them.
                pass
            chapters_by_id[chapter_id] = (work_id, chapter, path)

        # The original Ulysses mirror has a top-level note manifest. Once a
        # work supplies its own generated layout, discover that layout's
        # complete note directory so generated Genius IDs are validated too.
        note_manifest_path = (
            BASE_DIR / "data" / "notes.json"
            if work_id == "ulysses" and (work.get("legacy_paths") or {}).get("notes")
            else None
        )
        if note_manifest_path and note_manifest_path.exists():
            try:
                note_ids = [item.get("id") for item in load_json(note_manifest_path)]
            except Exception as exc:
                errors.append(f"{note_manifest_path.relative_to(BASE_DIR)}: invalid JSON ({exc})")
                note_ids = []
            note_paths = [note_dir / f"{note_id}.json" for note_id in note_ids if note_id]
            note_paths = [path for path in note_paths if path.exists()]
            missing = len(note_ids) - len(note_paths)
            if missing:
                errors.append(f"{work_id}: {missing} note files listed in manifest are missing")
        else:
            note_paths = [
                path for path in sorted(note_dir.glob("*.json"))
                if path.name != "index.json"
            ] if note_dir.exists() else []
        for path in note_paths:
            try:
                note = load_json(path)
            except Exception as exc:
                errors.append(f"{path.relative_to(BASE_DIR)}: invalid JSON ({exc})")
                continue
            note_id = note.get("id")
            if not note_id:
                errors.append(f"{path.relative_to(BASE_DIR)}: note without id")
                continue
            if note_id in notes_by_id:
                errors.append(f"duplicate note id: {note_id}")
            notes_by_id[note_id] = (work_id, note, path)
            explicit_work = note.get("work_id")
            if explicit_work not in (None, work_id):
                errors.append(f"{path.relative_to(BASE_DIR)}: wrong work_id")
            if explicit_work is None:
                # The original Ulysses files predate the work-aware schema;
                # the browser adds this field when it loads them.
                pass
            chapter_id = note.get("chapter_id")
            if chapter_id and chapter_id not in chapters_by_id:
                errors.append(f"{path.relative_to(BASE_DIR)} points to missing chapter {chapter_id}")
            for media_id in note.get("media_doc_ids") or []:
                if media_id not in media_by_work.get(work_id, set()):
                    message = f"{path.relative_to(BASE_DIR)} points to missing media {media_id}"
                    if work_id == "ulysses":
                        warnings.append("legacy: " + message)
                    else:
                        errors.append(message)

    # Notes are independently rendered HTML too; check their structure before
    # validating chapter references.
    for note_id, (work_id, note, path) in notes_by_id.items():
        source = note.get("html_source")
        if not isinstance(source, str) or not source.strip():
            errors.append(f"{path.relative_to(BASE_DIR)} has no html_source")
            continue
        parser = StructureParser()
        try:
            parser.feed(source)
            parser.close()
        except Exception as exc:
            errors.append(f"{path.relative_to(BASE_DIR)}: malformed HTML ({exc})")
        for issue in parser.errors:
            errors.append(f"{path.relative_to(BASE_DIR)}: {issue}")

    # Validate each chapter's generated HTML and all references/ranges.
    for chapter_id, (work_id, chapter, path) in chapters_by_id.items():
        source = chapter.get("html_source")
        if not isinstance(source, str) or not source.strip():
            errors.append(f"{path.relative_to(BASE_DIR)} has no html_source")
            continue
        parser = StructureParser()
        try:
            parser.feed(source)
            parser.close()
        except Exception as exc:
            errors.append(f"{path.relative_to(BASE_DIR)}: malformed HTML ({exc})")
        for issue in parser.errors:
            errors.append(f"{path.relative_to(BASE_DIR)}: {issue}")
        for href, ids, raw in parser.references:
            if not ids:
                errors.append(f"{path.relative_to(BASE_DIR)}: annotation anchor has no note ids")
                continue
            if len(ids) != len(set(ids)):
                errors.append(f"{path.relative_to(BASE_DIR)}: duplicate id in data-notes")
            for note_id in ids:
                record = notes_by_id.get(note_id)
                if not record:
                    message = f"{path.relative_to(BASE_DIR)}: missing note reference {note_id}"
                    if work_id == "ulysses":
                        warnings.append("legacy: " + message)
                    else:
                        errors.append(message)
                    continue
                note_work, note, note_path = record
                if note_work != work_id:
                    errors.append(f"{path.relative_to(BASE_DIR)}: note {note_id} belongs to {note_work}")
                if note.get("chapter_id") and note.get("chapter_id") != chapter_id:
                    errors.append(f"{path.relative_to(BASE_DIR)}: note {note_id} assigned to wrong chapter")

        ranges = chapter.get("annotation_ranges") or []
        plain = visible_text(source)
        for item in ranges:
            note_id = item.get("note_id")
            record = notes_by_id.get(note_id)
            if not record:
                errors.append(f"{path.relative_to(BASE_DIR)}: range references missing note {note_id}")
                continue
            note_work, note, note_path = record
            if note_work != work_id or note.get("chapter_id") != chapter_id:
                errors.append(f"{path.relative_to(BASE_DIR)}: range note {note_id} has wrong chapter/work")
            start, end = item.get("start"), item.get("end")
            if not isinstance(start, int) or not isinstance(end, int) or not (0 <= start < end <= len(plain)):
                errors.append(f"{path.relative_to(BASE_DIR)}: invalid range for {note_id}")
                continue
            intended = item.get("text") or (note.get("anchor") or {}).get("canonical_text") or (note.get("anchor") or {}).get("text")
            if intended and normalized(plain[start:end]) != normalized(html.unescape(str(intended))):
                errors.append(f"{path.relative_to(BASE_DIR)}: range text mismatch for {note_id}")

    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true", help="only print failures")
    args = parser.parse_args()
    errors, warnings = validate()
    if not args.quiet:
        for warning in warnings:
            print("warning:", warning)
    if errors:
        print(f"Validation failed: {len(errors)} error(s)", file=sys.stderr)
        for error in errors:
            print("error:", error, file=sys.stderr)
        return 1
    print(f"Validation passed: {len(warnings)} compatibility warning(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
